### ISSUE TITLE
Bad Request (HTTP 400)

### ISSUE THREAD

**Issue by JimboMahoney** [JoeFernando/rIG#5]
Hi Joe!

Firstly, thanks for putting this code together - it gives me somewhere to start.

All I want to be able to do it login to my IG account and pull in the active positions.

I've tried your `ig_login()` function, but I get the following when using the correct login/password/api key:

` Error in ig_login(b, api) : Bad Request (HTTP 400). `

If I change the api key, I get:

`Error in ig_login(b, api) : Forbidden (HTTP 403)`

If I change the login name, I get:

`Error in ig_login(b, api) : Unauthorized (HTTP 401).`

The code I'm running is:

```
b   <- '{"identifier":"mylogin", "password": "mypassword"}'
api <- "myAPIkey"
ig_login(b, api) 
```

Any ideas will be appreciated! (I'm fairly new to R and HTML!)

**Comment by JimboMahoney** [comment]
OK, I managed to get "Login is good".

I may have just been missing a package - rlist.

I'll close this for now and see what other progress I can make...

**Comment by JimboMahoney** [comment]
I've created a basic repository of code snippets that are working for me but given you credit for the code:

https://github.com/JimboMahoney/rIG

Hope this is OK!

**Comment by JoeFernando** [comment]
@JimboMahoney Apologies mate, I completely did not see this...been a long time since I visited this page. The package has evolved since what is on here. I'll delete this and put up the new code soon. Glad it was of use to you.
